CREATE TABLE GALAXIES (
 type INTEGER NOT NULL 
,  haloIndex INTEGER NOT NULL 
,  snapNum INTEGER NOT NULL 
,  lookBackTimeToSnap REAL NOT NULL 
,  centralMvir REAL NOT NULL 
,  centralRvir REAL NOT NULL 
,  distanceToCentralGal_1 REAL NOT NULL 
,  distanceToCentralGal_2 REAL NOT NULL 
,  distanceToCentralGal_3 REAL NOT NULL 
,  pos_1 REAL NOT NULL 
,  pos_2 REAL NOT NULL 
,  pos_3 REAL NOT NULL 
,  vel_1 REAL NOT NULL 
,  vel_2 REAL NOT NULL 
,  vel_3 REAL NOT NULL 
,  len INTEGER NOT NULL 
,  mvir REAL NOT NULL 
,  rvir REAL NOT NULL 
,  vvir REAL NOT NULL 
,  vmax REAL NOT NULL 
,  gasSpin_1 REAL NOT NULL 
,  gasSpin_2 REAL NOT NULL 
,  gasSpin_3 REAL NOT NULL 
,  stellarSpin_1 REAL NOT NULL 
,  stellarSpin_2 REAL NOT NULL 
,  stellarSpin_3 REAL NOT NULL 
,  infallVmax REAL NOT NULL 
,  infallVmaxPeak REAL NOT NULL 
,  infallSnap INTEGER NOT NULL 
,  infallHotGas REAL NOT NULL 
,  hotRadius REAL NOT NULL 
,  oriMergTime REAL NOT NULL 
,  mergTime REAL NOT NULL 
,  coldGas REAL NOT NULL 
,  stellarMass REAL NOT NULL 
,  bulgeMass REAL NOT NULL 
,  diskMass REAL NOT NULL 
,  hotGas REAL NOT NULL 
,  ejectedMass REAL NOT NULL 
,  blackHoleMass REAL NOT NULL 
,  iCM REAL NOT NULL 
,  metals struct NOT NULL 
,  metals struct NOT NULL 
,  metals struct NOT NULL 
,  metals struct NOT NULL 
,  metals struct NOT NULL 
,  metals struct NOT NULL 
,  primordialAccretionRate REAL NOT NULL 
,  coolingRadius REAL NOT NULL 
,  coolingRate REAL NOT NULL 
,  coolingRate_beforeAGN REAL NOT NULL 
,  quasarAccretionRate REAL NOT NULL 
,  radioAccretionRate REAL NOT NULL 
,  sfr REAL NOT NULL 
,  sfrBulge REAL NOT NULL 
,  xrayLum REAL NOT NULL 
,  bulgeSize REAL NOT NULL 
,  stellarDiskRadius REAL NOT NULL 
,  gasDiskRadius REAL NOT NULL 
,  cosInclination REAL NOT NULL 
,  disruptOn INTEGER NOT NULL 
,  mergeOn INTEGER NOT NULL 
,  magDust_1 REAL NOT NULL 
,  magDust_2 REAL NOT NULL 
,  magDust_3 REAL NOT NULL 
,  magDust_4 REAL NOT NULL 
,  magDust_5 REAL NOT NULL 
,  magDust_6 REAL NOT NULL 
,  magDust_7 REAL NOT NULL 
,  magDust_8 REAL NOT NULL 
,  magDust_9 REAL NOT NULL 
,  magDust_10 REAL NOT NULL 
,  magDust_11 REAL NOT NULL 
,  magDust_12 REAL NOT NULL 
,  magDust_13 REAL NOT NULL 
,  magDust_14 REAL NOT NULL 
,  magDust_15 REAL NOT NULL 
,  magDust_16 REAL NOT NULL 
,  magDust_17 REAL NOT NULL 
,  magDust_18 REAL NOT NULL 
,  magDust_19 REAL NOT NULL 
,  magDust_20 REAL NOT NULL 
,  magDust_21 REAL NOT NULL 
,  magDust_22 REAL NOT NULL 
,  magDust_23 REAL NOT NULL 
,  magDust_24 REAL NOT NULL 
,  magDust_25 REAL NOT NULL 
,  magDust_26 REAL NOT NULL 
,  magDust_27 REAL NOT NULL 
,  magDust_28 REAL NOT NULL 
,  magDust_29 REAL NOT NULL 
,  magDust_30 REAL NOT NULL 
,  magDust_31 REAL NOT NULL 
,  magDust_32 REAL NOT NULL 
,  magDust_33 REAL NOT NULL 
,  magDust_34 REAL NOT NULL 
,  magDust_35 REAL NOT NULL 
,  magDust_36 REAL NOT NULL 
,  magDust_37 REAL NOT NULL 
,  magDust_38 REAL NOT NULL 
,  magDust_39 REAL NOT NULL 
,  magDust_40 REAL NOT NULL 
,  mag_1 REAL NOT NULL 
,  mag_2 REAL NOT NULL 
,  mag_3 REAL NOT NULL 
,  mag_4 REAL NOT NULL 
,  mag_5 REAL NOT NULL 
,  mag_6 REAL NOT NULL 
,  mag_7 REAL NOT NULL 
,  mag_8 REAL NOT NULL 
,  mag_9 REAL NOT NULL 
,  mag_10 REAL NOT NULL 
,  mag_11 REAL NOT NULL 
,  mag_12 REAL NOT NULL 
,  mag_13 REAL NOT NULL 
,  mag_14 REAL NOT NULL 
,  mag_15 REAL NOT NULL 
,  mag_16 REAL NOT NULL 
,  mag_17 REAL NOT NULL 
,  mag_18 REAL NOT NULL 
,  mag_19 REAL NOT NULL 
,  mag_20 REAL NOT NULL 
,  mag_21 REAL NOT NULL 
,  mag_22 REAL NOT NULL 
,  mag_23 REAL NOT NULL 
,  mag_24 REAL NOT NULL 
,  mag_25 REAL NOT NULL 
,  mag_26 REAL NOT NULL 
,  mag_27 REAL NOT NULL 
,  mag_28 REAL NOT NULL 
,  mag_29 REAL NOT NULL 
,  mag_30 REAL NOT NULL 
,  mag_31 REAL NOT NULL 
,  mag_32 REAL NOT NULL 
,  mag_33 REAL NOT NULL 
,  mag_34 REAL NOT NULL 
,  mag_35 REAL NOT NULL 
,  mag_36 REAL NOT NULL 
,  mag_37 REAL NOT NULL 
,  mag_38 REAL NOT NULL 
,  mag_39 REAL NOT NULL 
,  mag_40 REAL NOT NULL 
,  magBulge_1 REAL NOT NULL 
,  magBulge_2 REAL NOT NULL 
,  magBulge_3 REAL NOT NULL 
,  magBulge_4 REAL NOT NULL 
,  magBulge_5 REAL NOT NULL 
,  magBulge_6 REAL NOT NULL 
,  magBulge_7 REAL NOT NULL 
,  magBulge_8 REAL NOT NULL 
,  magBulge_9 REAL NOT NULL 
,  magBulge_10 REAL NOT NULL 
,  magBulge_11 REAL NOT NULL 
,  magBulge_12 REAL NOT NULL 
,  magBulge_13 REAL NOT NULL 
,  magBulge_14 REAL NOT NULL 
,  magBulge_15 REAL NOT NULL 
,  magBulge_16 REAL NOT NULL 
,  magBulge_17 REAL NOT NULL 
,  magBulge_18 REAL NOT NULL 
,  magBulge_19 REAL NOT NULL 
,  magBulge_20 REAL NOT NULL 
,  magBulge_21 REAL NOT NULL 
,  magBulge_22 REAL NOT NULL 
,  magBulge_23 REAL NOT NULL 
,  magBulge_24 REAL NOT NULL 
,  magBulge_25 REAL NOT NULL 
,  magBulge_26 REAL NOT NULL 
,  magBulge_27 REAL NOT NULL 
,  magBulge_28 REAL NOT NULL 
,  magBulge_29 REAL NOT NULL 
,  magBulge_30 REAL NOT NULL 
,  magBulge_31 REAL NOT NULL 
,  magBulge_32 REAL NOT NULL 
,  magBulge_33 REAL NOT NULL 
,  magBulge_34 REAL NOT NULL 
,  magBulge_35 REAL NOT NULL 
,  magBulge_36 REAL NOT NULL 
,  magBulge_37 REAL NOT NULL 
,  magBulge_38 REAL NOT NULL 
,  magBulge_39 REAL NOT NULL 
,  magBulge_40 REAL NOT NULL 
,  massWeightAge REAL NOT NULL 
,  elements_1 struct NOT NULL 
,  elements_2 struct NOT NULL 
,  elements_3 struct NOT NULL 
,  elements_4 struct NOT NULL 
,  elements_5 struct NOT NULL 
,  elements_6 struct NOT NULL 
,  elements_7 struct NOT NULL 
,  elements_8 struct NOT NULL 
,  elements_9 struct NOT NULL 
,  elements_10 struct NOT NULL 
,  elements_11 struct NOT NULL 
,  elements_12 struct NOT NULL 
,  elements_13 struct NOT NULL 
,  elements_14 struct NOT NULL 
,  elements_15 struct NOT NULL 
,  elements_16 struct NOT NULL 
,  elements_17 struct NOT NULL 
,  elements_18 struct NOT NULL 
,  elements_19 struct NOT NULL 
,  elements_20 struct NOT NULL 
,  elements_1 struct NOT NULL 
,  elements_2 struct NOT NULL 
,  elements_3 struct NOT NULL 
,  elements_4 struct NOT NULL 
,  elements_5 struct NOT NULL 
,  elements_6 struct NOT NULL 
,  elements_7 struct NOT NULL 
,  elements_8 struct NOT NULL 
,  elements_9 struct NOT NULL 
,  elements_10 struct NOT NULL 
,  elements_11 struct NOT NULL 
,  elements_12 struct NOT NULL 
,  elements_13 struct NOT NULL 
,  elements_14 struct NOT NULL 
,  elements_15 struct NOT NULL 
,  elements_16 struct NOT NULL 
,  elements_17 struct NOT NULL 
,  elements_18 struct NOT NULL 
,  elements_19 struct NOT NULL 
,  elements_20 struct NOT NULL 
,  elements_1 struct NOT NULL 
,  elements_2 struct NOT NULL 
,  elements_3 struct NOT NULL 
,  elements_4 struct NOT NULL 
,  elements_5 struct NOT NULL 
,  elements_6 struct NOT NULL 
,  elements_7 struct NOT NULL 
,  elements_8 struct NOT NULL 
,  elements_9 struct NOT NULL 
,  elements_10 struct NOT NULL 
,  elements_11 struct NOT NULL 
,  elements_12 struct NOT NULL 
,  elements_13 struct NOT NULL 
,  elements_14 struct NOT NULL 
,  elements_15 struct NOT NULL 
,  elements_16 struct NOT NULL 
,  elements_17 struct NOT NULL 
,  elements_18 struct NOT NULL 
,  elements_19 struct NOT NULL 
,  elements_20 struct NOT NULL 
,  elements struct NOT NULL 
,  elements struct NOT NULL 
,  elements struct NOT NULL 
,  elements struct NOT NULL 
,  elements struct NOT NULL 
,  elements struct NOT NULL 
,  elements struct NOT NULL 
,  attenuation_Dust REAL NOT NULL 
)
CREATE TABLE SFH_Times (
 snapnum INTEGER NOT NULL 
,  bin INTEGER NOT NULL 
,  lookbacktime double NOT NULL 
,  dt double NOT NULL 
,  nbins INTEGER NOT NULL 
 -- size = 20
)
